In [1]:
import numpy as np
import matplotlib as mpl
%matplotlib inline
import pandas as pd
import seaborn as sns

In [2]:
from sklearn.datasets import make_classification

In [3]:
import sys
sys.path.append('../code/')

In [4]:
from ridge_regression import RidgeBinary, RidgeMulti

In [5]:
X, y = np.array([[1, 2.], [4, 0], [4, 1]]), np.array([0, 1, 1])

## Multi-Class:

In [6]:
rm = RidgeMulti(X=X, y=y, lam=0)

In [7]:
rm.run()

In [8]:
rm.results

# nonzero weights  (0/1 loss)/N  0/1 loss      RMSE       SSE  lambda  \
0                  4           0.0         0  0.085973  0.022174       0   

                                             weights  
0  [[-0.0542635658915, 0.263565891473], [0.465116...

In [9]:
np.multiply(rm.Y, rm.X.dot(rm.W) - rm.Y)

array([[-0.12403101,  0.        ],
       [-0.        ,  0.05426357],
       [ 0.        , -0.0620155 ]])

In [10]:
0.124**2 + 0.05426357**2 + 0.0620155**2

0.022166457269394903

## Binary:

In [11]:
rrb = RidgeBinary(X=X, y=y, lam=0)
rrb.run()

In [12]:
rrb.threshold = 0.5

In [13]:
rrb.results

# nonzero weights  (0/1 loss)/N  0/1 loss      RMSE       SSE  lambda  \
0                  2           0.0         0  0.050833  0.007752       0   

                             weights  
0  [0.263565891473, -0.116279069767]

In [14]:
rrb.X

array([[ 1.,  2.],
       [ 4.,  0.],
       [ 4.,  1.]])

In [15]:
rrb.w

array([ 0.26356589, -0.11627907])

### Compare: 

They 2nd col of the multiclass's W

In [16]:
rm.W

array([[-0.05426357,  0.26356589],
       [ 0.46511628, -0.11627907]])

In [17]:
rrb.w

array([ 0.26356589, -0.11627907])

In [18]:
rm.apply_weights()

array([[ 0.87596899,  0.03100775],
       [-0.21705426,  1.05426357],
       [ 0.24806202,  0.9379845 ]])

In [19]:
rrb.apply_weights()

array([ 0.03100775,  1.05426357,  0.9379845 ])

In [20]:
(1-.87596899)**2 + (1-1.05426357)**2 + (1-0.9379845)**2

0.022174148711015015

In [21]:
rm.sse()

0.02217414818820981

Since 0.031 != 1- 0.8705, we get different SSEs. 

In [22]:
0.03100775**2 + (1-1.05426357)**2 + (1-0.9379845)**2

0.007751937829457404

In [23]:
rrb.sse()

0.0077519379844961239