In [1]:
import sys
sys.version
sys.version_info

sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)

In [2]:
import sys
sys.path.append('')

In [3]:
import scipy.sparse as sp
import numpy as np

In [4]:
from lasso import Lasso

In [5]:
# try the code used in the scikit-learn example. 
skl_ex_X = sp.csc_matrix([[0,0], [1, 1], [2, 2]])
skl_ex_Y = np.array([[0, 1, 2]]).T

In [6]:
toy = Lasso(X = skl_ex_X, 
            y = skl_ex_Y,
            lam = 0.1,
            w = sp.csc_matrix([[1, 99]]).T
           )

In [7]:
toy.optimize_weights()

begin optimizing weights
Testing convergence.
Old w: [[  1.02]
 [ 99.02]], new w: [[ 1]
 [99]]
Testing convergence.
Old w: [[  1.02]
 [ 99.02]], new w: [[ 1]
 [99]]
Calc X*w + w_0 for w =   (0, 0)	1
  (1, 0)	99, w_0=0.0
0 snuggle
ck: -980.0, lambda: 0.1
1 snuggle
ck: 0.0, lambda: 0.1
Testing convergence.
Old w: [[ 1]
 [99]], new w: [[-97]
 [  0]]
Calc X*w + w_0 for w =   (0, 0)	-97
  (1, 0)	0, w_0=0.0
0 snuggle
ck: 10.0, lambda: 0.1
1 snuggle
ck: 980.0, lambda: 0.1
Testing convergence.
Old w: [[-97]
 [  0]], new w: [[ 0]
 [97]]
Calc X*w + w_0 for w =   (0, 0)	0
  (1, 0)	97, w_0=0.0
0 snuggle
ck: -960.0, lambda: 0.1
1 snuggle
ck: 10.0, lambda: 0.1
Testing convergence.
Old w: [[ 0]
 [97]], new w: [[-95]
 [  0]]
Calc X*w + w_0 for w =   (0, 0)	-95
  (1, 0)	0, w_0=0.0
0 snuggle
ck: 10.0, lambda: 0.1
1 snuggle
ck: 960.0, lambda: 0.1
Testing convergence.
Old w: [[-95]
 [  0]], new w: [[ 0]
 [95]]
Calc X*w + w_0 for w =   (0, 0)	0
  (1, 0)	95, w_0=0.0
0 snuggle
ck: -940.0, lambda: 0.1
1 snugg

In [8]:
# try the code used in the scikit-learn example. 
m = sp.csc_matrix([[2,0], [1, 10]])
tmp = np.array([0, 1])

In [9]:
m.dot(tmp)

array([ 0, 10], dtype=int64)

In [10]:
m[:,1] + tmp

matrix([[ 0,  1],
        [10, 11]])

In [11]:
print(skl_ex_X.shape[0])
print(skl_ex_Y.shape)

3
(3, 1)


In [12]:
# try the code used in the scikit-learn example. 
m = sp.csc_matrix([[2,0], [1, 10]])
tmp = sp.csc_matrix([[0, 1]])

In [13]:
m[:,1]

<2x1 sparse matrix of type '<class 'numpy.int64'>'
	with 1 stored elements in Compressed Sparse Column format>

In [14]:
# try the code used in the scikit-learn example. 
m = sp.csc_matrix([[2,0], [1, 10]])
tmp = np.array([0, 1])

In [15]:
m[:,1].toarray()[:,0] # + tmp

array([ 0, 10])

In [16]:
m[:,1].toarray()[:,0] + tmp

array([ 0, 11])

In [17]:
# try the code used in the scikit-learn example. 
m = sp.csc_matrix([[2,0], [1, 10]])

In [21]:
tmp = sp.csc_matrix([[0, 1]]).T
print(tmp)

  (1, 0)	1


In [19]:
print(tmp.T)

  (0, 1)	1


In [20]:
x = m[:,1] + tmp.T
print(x.toarray())

ValueError: inconsistent shapes

In [ ]:
list(range(1,2))

In [ ]:
tmp.T.dot(tmp).shape == (1,1)

In [ ]:
x = tmp.copy()

In [ ]:
x[1,0] = 4

In [ ]:
print(x)

In [23]:
tmp.toarray()*2.3

array([[ 0. ],
       [ 2.3]])

In [ ]:
print(tmp)

In [ ]:
abs(-0.3)