In [1]:
import sys
sys.version
sys.version_info

sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)

In [2]:
import sys
sys.path.append('')

In [3]:
import scipy.sparse as sp
import numpy as np

In [4]:
from lasso import Lasso

In [5]:
# try the code used in the scikit-learn example. 
skl_ex_X = sp.csc_matrix([[0.,0], [1, 1], [2, 2]])
skl_ex_Y = np.array([[0, 1, 2]]).T

In [6]:
lasso_toy = Lasso(X = skl_ex_X, 
            y = skl_ex_Y,
            lam = 0.1,
            w = sp.csc_matrix([[0., 0.]]).T,
            delta = 0.001,
            verbose = True
           )
lasso_toy.optimize_weights()

begin optimizing weights
Testing convergence.
w:
[[ 0.]
 [ 0.]]
w0: 0.0
Testing convergence.
w:
[[ 0.]
 [ 0.]]
w0: 0.0
Calc X*w + w_0 for w =
[[ 0.]
 [ 0.]]
  and w0 = 0.0
current yhat prediction:
[[ 0.]
 [ 0.]
 [ 0.]]
-- new round of wk updates --
old_w:
[[ 0.]
 [ 0.]]
ck = 4.0 for k = 0, ak =10.0, lambda: 0.1
self.w[k]: 0.0
ck > self.lam, so update w[0] from 0.0
new w[0]: 0.39
ck = 3.9000000000000004 for k = 1, ak =10.0, lambda: 0.1
self.w[k]: 0.0
ck > self.lam, so update w[1] from 0.0
new w[1]: 0.38
weights for this loop:
[[ 0.39]
 [ 0.38]]
Testing convergence.
w:
[[ 0.39]
 [ 0.38]]
w0: 1.0
Calc X*w + w_0 for w =
[[ 0.39]
 [ 0.38]]
  and w0 = 1.0
current yhat prediction:
[[ 1.  ]
 [ 1.77]
 [ 2.54]]
-- new round of wk updates --
old_w:
[[ 0.39]
 [ 0.38]]
ck = 4.82 for k = 0, ak =10.0, lambda: 0.1
self.w[k]: 0.39
ck > self.lam, so update w[0] from 0.39
new w[0]: 0.4720000000000001
ck = 4.620000000000001 for k = 1, ak =10.0, lambda: 0.1
self.w[k]: 0.38
ck > self.lam, so update w[1] fro

/Users/janet/miniconda3/envs/mlpy3/lib/python3.5/site-packages/scipy/sparse/compressed.py:730: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  SparseEfficiencyWarning)


ck > self.lam, so update w[0] from 0.6112499999999997
new w[0]: 0.6162499999999997
ck = 3.562500000000002 for k = 1, ak =10.0, lambda: 0.1
self.w[k]: 0.35125000000000023
ck > self.lam, so update w[1] from 0.35125000000000023
new w[1]: 0.3462500000000002
weights for this loop:
[[ 0.61625]
 [ 0.34625]]
Testing convergence.
w:
[[ 0.61625]
 [ 0.34625]]
w0: 0.037500000000000096
Calc X*w + w_0 for w =
[[ 0.61625]
 [ 0.34625]]
  and w0 = 0.037500000000000096
current yhat prediction:
[[ 0.0375]
 [ 1.    ]
 [ 1.9625]]
-- new round of wk updates --
old_w:
[[ 0.61625]
 [ 0.34625]]
ck = 6.312499999999998 for k = 0, ak =10.0, lambda: 0.1
self.w[k]: 0.6162499999999997
ck > self.lam, so update w[0] from 0.6162499999999997
new w[0]: 0.6212499999999999
ck = 3.5125000000000033 for k = 1, ak =10.0, lambda: 0.1
self.w[k]: 0.3462500000000002
ck > self.lam, so update w[1] from 0.3462500000000002
new w[1]: 0.34125000000000033
weights for this loop:
[[ 0.62125]
 [ 0.34125]]
Testing convergence.
w:
[[ 0.62125]

In [7]:
print(lasso_toy.w.toarray())
print("")
print(lasso_toy.w0)
print("")
print(lasso_toy.calculate_yhat())

[[ 0.973866]
 [ 0.      ]]

0.02689

Calc X*w + w_0 for w =
[[ 0.973866]
 [ 0.      ]]
  and w0 = 0.026889999999999813
current yhat prediction:
[[ 0.02689 ]
 [ 1.000756]
 [ 1.974622]]
[[ 0.02689 ]
 [ 1.000756]
 [ 1.974622]]


# Compare to sklearn

In [8]:
from sklearn import linear_model
lam = 0.1
alpha = lam/(2*3)  # hard coded for 3 sample points. 
clf = linear_model.Lasso(alpha)  # 3 samples  http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Lasso.html
clf.fit([[0.,0], [1, 1], [2, 2]], [0., 1, 2])

print(clf.coef_)
print(clf.intercept_)
print(clf.predict([[0.,0], [1, 1], [2, 2]]))


[  9.75000000e-01   4.16333634e-17]
0.025
[ 0.025  1.     1.975]


In [9]:
def calc_objective_fun(X, y, w, w0, lam):
    #import pdb; pdb.set_trace()
    preds = X.dot(w) + np.ones((X.shape[0], 1))*w0
    pred_error = preds - y
    preds_error_squared = pred_error.T.dot(pred_error)[0,0]
    weights = w.toarray()[:,0]
    weight_magnitudes = [abs(w) for w in weights]
    penalty = lam * sum(weight_magnitudes)
    return preds_error_squared + penalty

In [10]:
calc_objective_fun(X = skl_ex_X, y = skl_ex_Y, w = sp.csc_matrix([clf.coef_]).T, w0= clf.intercept_, lam=lam)

0.098750000000000004

# High-printing test case

In [11]:
# try the code used in the scikit-learn example. 
toy_X = sp.csc_matrix([[0.,1], [1, 2], [2, 3]])
toy_Y = np.array([[2., 5, 8]]).T

In [12]:
toy = Lasso(X = toy_X, 
            y = toy_Y,
            lam = 0.1,
            w = sp.csc_matrix([[0., 0.]]).T,
            verbose = True
           )

In [13]:
toy.optimize_weights()

begin optimizing weights
Testing convergence.
w:
[[ 0.]
 [ 0.]]
w0: 0.0
Testing convergence.
w:
[[ 0.]
 [ 0.]]
w0: 0.0
Calc X*w + w_0 for w =
[[ 0.]
 [ 0.]]
  and w0 = 0.0
current yhat prediction:
[[ 0.]
 [ 0.]
 [ 0.]]
-- new round of wk updates --
old_w:
[[ 0.]
 [ 0.]]
ck = 12.0 for k = 0, ak =10.0, lambda: 0.1
self.w[k]: 0.0
ck > self.lam, so update w[0] from 0.0
new w[0]: 1.19
ck = 19.04 for k = 1, ak =28.0, lambda: 0.1
self.w[k]: 0.0
ck > self.lam, so update w[1] from 0.0
new w[1]: 0.6764285714285714
weights for this loop:
[[ 1.19      ]
 [ 0.67642857]]
Testing convergence.
w:
[[ 1.19      ]
 [ 0.67642857]]
w0: 5.0
Calc X*w + w_0 for w =
[[ 1.19      ]
 [ 0.67642857]]
  and w0 = 5.0
current yhat prediction:
[[ 5.67642857]
 [ 7.54285714]
 [ 9.40928571]]
-- new round of wk updates --
old_w:
[[ 1.19      ]
 [ 0.67642857]]
ck = 16.434285714285714 for k = 0, ak =10.0, lambda: 0.1
self.w[k]: 1.19
ck > self.lam, so update w[0] from 1.19
new w[0]: 1.6334285714285712
ck = 26.034857142857135

/Users/janet/miniconda3/envs/mlpy3/lib/python3.5/site-packages/scipy/sparse/compressed.py:730: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  SparseEfficiencyWarning)


In [14]:
from sklearn import linear_model
lam = 0.1
alpha = lam/(2*3)  # hard coded for 3 sample points. 
clf = linear_model.Lasso(alpha)  # 3 samples  http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Lasso.html
clf.fit([[0.,1], [1, 2], [2, 3]], [2., 5, 8])

print(clf.coef_)
print(clf.intercept_)
print(clf.predict([[0.,1], [1, 2], [2, 3]]))


[ 2.975  0.   ]
2.025
[ 2.025  5.     7.975]
